### ISSUE TITLE
Not able to connect with device when hitting "connect"

### ISSUE THREAD

**Issue by DeTovergieter** [openpst/sahara#17]
Clicking the connect button isn't doing anything for me. I'm running on Virtualbox as I don't have a Linux machine (I have all the USB drivers though so this shouldn't be the cause) but although it can see the device and it is listed in the dropdown selection, it is unable to connect to it. Clicking connect does nothing and the device stays unconnected. I'd really like to see the logs from my device to see what's going on, and this tool is the only one that can even grab info like that so I'd really love to get it working if possible.

**Comment by DeTovergieter** [comment]
Ok, I finally got it to connect after installing the drivers "51-edl.rules" and "50-android.rules" from this other project: https://github.com/bkerler/edl
So that's good. Not able to get any logs or answers from the commands yet even though it connects and even goes into "command mode" but I'll give it another try at getting it to work later. Cheers.

**Comment by ghassani** [comment]
It is possible commands are stripped or changed in your device build. While this is usually not the case its a possibility. It also could have something to do with doing it from a VM. I would suggest you use a tool like wireshark or some other packet capture to see whats really going on. You can share them and i will take a look if you want.

Also, the log feature just dumps a binary blob, i never got around to figuring out that structure. Its not really useful in its current state to be honest. However, if you are in EDL mode (9008), the log wont help anyway - you need to send over a valid programmer for your device to re-initialize the emmc. There isnt anything else you can do that is useful in sahara while in this state.

Also there are divers, rules, and other stuff in this repository for future reference:

https://github.com/openpst/assets
