### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by Runemoro** [openpst/sahara#2]
I get the following error while compiling on Windows:

`g++  -o ../../sahara/build/release/sahara.exe ../../sahara/build/release/obj/task_runner.o ../../sahara/build/release/obj/log_widget.o ../../sahara/build/release/obj/progress_group_widget.o ../../sahara/build/release/obj/table_dialog.o ../../sahara/build/release/obj/about_dialog.o ../../sahara/build/release/obj/application.o ../../sahara/build/release/obj/sahara_window.o ../../sahara/build/release/obj/sahara_image_transfer_task.o ../../sahara/build/release/obj/sahara_memory_read_task.o ../../sahara/build/release/obj/main.o ../../sahara/build/release/obj/qrc_sahara.o ../../sahara/build/release/obj/moc_task.o ../../sahara/build/release/obj/moc_log_widget.o ../../sahara/build/release/obj/moc_progress_group_widget.o ../../sahara/build/release/obj/moc_table_dialog.o ../../sahara/build/release/obj/moc_about_dialog.o ../../sahara/build/release/obj/moc_sahara_window.o   -L/cygdrive/c/Users/Stefan/Desktop/GitHub/openpst/sahara/build/release/lib -lopenpst -lQt5Widgets -lQt5Gui -lQt5Xml -lQt5Core -lGL -lpthread
../../sahara/build/release/obj/sahara_window.o:sahara_window.cpp:(.text+0x3c84): undefined reference to `serial::list_ports()'
../../sahara/build/release/obj/sahara_window.o:sahara_window.cpp:(.text+0x3c84): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `serial::list_ports()'
../../sahara/build/release/obj/sahara_window.o:sahara_window.cpp:(.text+0x3e15): undefined reference to `serial::list_ports()'
../../sahara/build/release/obj/sahara_window.o:sahara_window.cpp:(.text+0x3e15): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `serial::list_ports()'
../../sahara/build/release/obj/sahara_window.o:sahara_window.cpp:(.text+0x76ad): undefined reference to `serial::list_ports()'
../../sahara/build/release/obj/sahara_window.o:sahara_window.cpp:(.text+0x76ad): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `serial::list_ports()'
collect2: error: ld returned 1 exit status`

**Comment by ghost** [comment]
On ubuntu you need to run this.  Try to find qt and boost for windows.

`sudo apt-get install build-essential qt5-default qt5-qmake libboost-dev
`

**Comment by ghassani** [comment]
I have provided Linux x64 builds in the releases page for master branch for now
